server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://apps-gateway.herokuapp.com/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: